DELETE  http://localhost:3001/api/persons/661ea185e7ed0c99c115c4a1

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Farukkk" ,
    "number": "353453453"
}
